### ISSUE TITLE
关于库代码的7点问题

### ISSUE THREAD

**Issue by kaleai** [sfsheng0322/MultiType#1]
### 1. 为什么要在application中注册

在application中少做事情是众所周知的事情，在app收到推送的时候，application会自动唤醒，也就是会执行注册工作，而这种工作在这种情况毫无意义

### 2. 为什么要分散定义

注册和使用本应该是在一起的，有内聚性，这种分开的方案弄得全部分散，做一件事情要到多个文件中进行，可读性差。java的混淆对于内聚性强的代码可以自动优化，而这种则完全不行。

静态注册的方式，如果你没有地方使用这个类型，但忘记手动删除注册的代码，混淆机制无法自动帮助你进行优化，总之这种设计思路显得十分的愚蠢。

如果是插件化或者组件化，item都是对application不可见的，是内部逻辑，故注册的逻辑不可行。

### 3. 布局和数据对应问题

布局和数据一对一这个就不进行讨论了，这是基础概念，单一数据对多个布局也很简单。

单一布局对应多个数据这其实有两种解决策略：

- 做一个转换器（桥接器）对item这个java对象抹平数据差异
- 复用layout这个xml文件，对不同数据用java层不同的item对象

### 4.  关于空状态

这个库将空状态提供出去让使用者使用这是一个很好的思路，但是有如下几点需要主义：

- 空状态在有头部时的展示方式，emptyView高度应该是屏幕高度- 头部高度
- 能否提供添加头部和底部的方法，addHeader()和addFooter()方法添加多个头
- 能否提供动态移除头部和底部的方法，removeHeader(index)和removeFooter(index)

### 5. 关于库依赖的写法

2018年末，也就是今年末将不再支持`compile`的写法，建议库作者进行更换，而且尽量不要提供`api`的依赖方式。

一般提供开源库不需要提供exclude的方案，你仅仅需要将你不希望提供给使用者的recyclerView依赖变成comipleOnly的即可。

### 6. 关于ItemViewBinder的写法

ItemViewBinder理解上就是viewholder，做的一些事情。但他做了viewholder的定义和绑定工作，这里不建议这么做。这个使用起来其实很复杂的，建议在框架层面将viewholder的绑定工作做好，这里仅仅做view的findview和setAttr即可。

### 7.关于方法引用

ReadMe中提到：

> 这里通过Java8的特性传递方法的引用，再通过KeyGenerator执行这个方法获取数据对应的值来解决这个问题的。

这个在代码中没有找到具体的实现，想了解下实现的策略，如果是java8的特性，那么引入到java6的工程中是否需要做任何配置处理，还望具体告知，谢谢。

**Comment by sunfusheng** [comment]
首先感谢你这么认真的反馈，我也逐条回复吧，不妥的地方还请多指教
**1. 为什么要在application中注册**
注册全局类型不一定在application中注册，如果注册了也不会产生什么影响，new的ItemViewBinder只是一个引用。
**2. 为什么要分散定义**
这一条从代码的聚合性和app的安全性提出的见解我是比较认同的
**3. 布局和数据对应问题**
你说的这种方式，以前我们也都是这么搞的，MultiType只是提供一种更方便的解决办法，不一定符合所有的case。
**4. 关于空状态**
这条你应该说的是MultiState这个库，这个库只是处理多种状态，空状态或者错误状态显示的样式和操作逻辑还是交给具体的工程师去处理，不会添加addHeader和addFooter的。
**5. 关于库依赖的写法**
下一版优化
**6. 关于ItemViewBinder的写法**
ItemViewBinder主要是将数据Item和View绑定起来统一处理，好处显而易见，缺点可能提高开发的复杂性。
**7.关于方法引用**
不需要添加额外的配置，在库里面已经添加Java8，具体实现参考这两个文件MultiType和MultiTypePool。
