### ISSUE TITLE
多语言支持

### ISSUE THREAD

**Issue by liupeng826** [sfsheng0322/MultiType#2]
非常感谢这么好的库，能不能支持多语言？或者能在外面替换？

**Comment by liupeng826** [comment]
另外，如果Item内有按钮的话，支持按钮点击事件吗？

**Comment by sunfusheng** [comment]
等更加完善更加健壮的，会支持Kotlin的，
Item内有按钮不支持点击事件，需要在自己的ItemViewBinder内处理

**Comment by liupeng826** [comment]
不好意思我没说明白，类似正在加载中 这些字符串能在外面替换成英文或者其他语言吗？国际化

**Comment by sunfusheng** [comment]
好的，也建议你新建一个自己的加载布局
